steps:
  # 1. Run unit tests
  - id: 'unit tests'
    name: maven:3-jdk-8
    entrypoint: mvn
    args: ['test', '-Pall']
    env:
      - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
      - 'TEMPORARY_GCS_BUCKET=${_TEMPORARY_GCS_BUCKET}'

  # 2. Run integration tests
 # - name: 'gcr.io/$PROJECT_ID/dataproc-spark-bigquery-connector-presubmit'
 #   id: 'integration-tests'
 #   entrypoint: 'sbt'
 #   args: ['it:test']
 #   env:
 #     - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
 #     - 'TEMPORARY_GCS_BUCKET=${_TEMPORARY_GCS_BUCKET}'

# Tests take around 20 mins in general.
timeout: 1800s
