steps:
  # 1. Run unit and integration tests on DSv1
  - id: 'DataSource v1'
    name: maven:3-jdk-8
    entrypoint: mvn
    args: ['verify', '-Pdsv1_2.11,integration']
    env:
      - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
      - 'TEMPORARY_GCS_BUCKET=${_TEMPORARY_GCS_BUCKET}'

  # 2. Run unit tests on on DSv2, integration tests fail still
  - id: 'DataSource v2'
    name: maven:3-jdk-8
    entrypoint: mvn
    args: ['test' ,'-Pdsv2']
    env:
      - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
      - 'TEMPORARY_GCS_BUCKET=${_TEMPORARY_GCS_BUCKET}'

# Tests take around 20 mins in general.
timeout: 1800s
