steps:
  # 1. Run unit tests
  - id: 'unit tests'
    name: maven:3-jdk-8
    entrypoint: mvn
    args: ['install', '-Pall']
    env:
      - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
      - 'TEMPORARY_GCS_BUCKET=${_TEMPORARY_GCS_BUCKET}'

  # 2. Run integration tests
  - name: maven:3-jdk-8
    id: 'integration-tests'
    entrypoint: mvn
    args: ['failsafe:integration-test' ,'-Pdsv1_2.11,integration']
    env:
      - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
      - 'TEMPORARY_GCS_BUCKET=${_TEMPORARY_GCS_BUCKET}'

# Tests take around 20 mins in general.
timeout: 1800s
