steps:
  # 1. Create a Docker image containing hadoop-connectors repo
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/dataproc-spark-bigquery-connector-nightly', '-f', 'cloudbuild/Dockerfile', '.']

# 2. Fetch maven and dependencies
  - name: 'gcr.io/$PROJECT_ID/dataproc-spark-bigquery-connector-nightly'
    id: 'maven-build'
    entrypoint: 'bash'
    args: ['/workspace/cloudbuild/nightly.sh']
    env:
      - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
      - 'TEMPORARY_GCS_BUCKET=${_TEMPORARY_GCS_BUCKET}'
      - 'ACCEPTANCE_TEST_BUCKET=${_ACCEPTANCE_TEST_BUCKET}'
      - 'SERVERLESS_NETWORK_URI=${_SERVERLESS_NETWORK_URI}'
      - 'CODECOV_TOKEN=${_CODECOV_TOKEN}'
      - 'SONAR_TOKEN=${_SONAR_TOKEN}'

# Tests take around 20 mins in general.
timeout: 3600s

options:
  machineType: 'N1_HIGHCPU_32'
