name: Spotless Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        java-version: 8
    - name: Spotless check
      run: ./mvnw spotless:check
